language:
  - ruby
rvm:
  - 2.4.4
language: node_js
node_js:
  - '8'
  - '6'
  - '4'
sudo: true
notifications:
  slack: shakacode:YvfXbuFMcFAHt6ZjABIs0KET
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
services:
  - postgresql
env:
  global:
    - RAILS_ENV=test
    - CXX=g++-4.9
install:
  - bundle install
  - chromedriver-update
  - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - nvm install stable && nvm alias default stable
  - npm install -g npm@5.6.x
  - npm install -g yarn
  - node --version
  - npm --version
  - google-chrome --version
  - chromedriver --version
  - yarn install
  - rake db:setup

# Tip: No need to run xvfb if running headless testing. However, we're going to start with
# Poltergeist and switch to selenium if a test fails.
before_script:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake db:schema:load
  - bundle exec rake
