language:
  - ruby
rvm:
  - 2.3.1
sudo: false
addons:
  sauce_connect:
    username: "judahmeek"
  jwt:
    secure: "A/bVoePCHtwLGH4wVLCHK39+tml2axc/M/Mjnpg4m4bjgMI7GD4YqlnZMNrUBzNAv+Q66pp0sWjTy/Xm4tDaYnSxJFrWjD2wn5ZPpMEyB162nR+QqYqWl5DqP+jlOuIK+7iRmrRTlDS4LLTl43+nWxvRB16aat2U01P/+GKtQ+o="
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
services:
  - postgresql
env:
  global:
    - RAILS_ENV=test
    - CXX=g++-4.9
    - SAUCE_LABS_URL=http://judahmeek:1ed6d81c-c3e0-4fd0-9012-1d2274c4b261@ondemand.saucelabs.com:80/wd/hub
before_install:
  - mkdir $PWD/travis-phantomjs
  - curl -sSL https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2 -o $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
install:
  - bundle install
  - nvm install 6.7
  - nvm use 6.7
  - npm install
  - rake db:setup
# No need to run xvfb if running headless testing
#before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake db:schema:load
  - DRIVER=selenium_firefox bundle exec rake
  - bundle exec rake
