---
- include: package.yml
  when: ruby_install == 'package'

- include: rvm.yml
  when: ruby_install == 'rvm'

- include: rbenv.yml
  when: ruby_install == 'rbenv'

- name: Install bundler
  command: /bin/bash -l -c 'gem install bundler --no-ri --no-rdoc'
  sudo_user: '{{ ruby_user_name }}'

- name: bundle install
  command: /bin/bash -l -c 'bundle install' chdir={{ app_path }}
  sudo_user: '{{ ruby_user_name }}'
  when: target == 'virtualbox'
