---
- name: checkout nvm_repo for selected users
  git: >
    repo={{ nvm_repo }}
    dest={{ nvm_root }}
    version={{ nvm_version }}
    accept_hostkey=true
  with_items: nvm_users
  sudo: true
  sudo_user: "{{ item }}"
